version: '3.4'
services:
  dev-image:
    image: eagle1/crypto/develop-win:v1
    build:
      context: .
      network: host
      target: windows
    ports:
      - "2000:2000"
    privileged: false
    cap_add: 
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    container_name: crypto-devenv
    volumes:
      - "../../:/home/develop/eagle"