#include <logger.drone.hpp>

#include <LoggerValues.hpp>

/**
 * @brief   Rather sketchy conversion from a struct of primitives of the same
 *          type to a reference of an array of this type.
 * 
 * @tparam  ArrayElementType
 *          The type of the elements of the result array.
 * @tparam  StructType
 *          The type of the struct to convert. Make sure that the struct is 
 *          well packed, and that the memory layout is consistent with that of
 *          an array. 
 */
template <class ArrayElementType = float, class StructType = void>
static ArrayElementType (&toCppArray(
    StructType &data))[sizeof(StructType) / sizeof(ArrayElementType)] {
    static_assert(sizeof(StructType) % sizeof(ArrayElementType) == 0);
    return reinterpret_cast<
        ArrayElementType(&)[sizeof(StructType) / sizeof(ArrayElementType)]>(
        data);
}

/**
 * @brief   Rather sketchy conversion from a struct of primitives of the same
 *          type to a reference of an array of this type.
 * 
 * @tparam  ArrayElementType
 *          The type of the elements of the result array.
 * @tparam  StructType
 *          The type of the struct to convert. Make sure that the struct is 
 *          well packed, and that the memory layout is consistent with that of
 *          an array. 
 */
template <class ArrayElementType = float, class StructType = void>
static const ArrayElementType (&toCppArray(
    const StructType &data))[sizeof(StructType) / sizeof(ArrayElementType)] {
    static_assert(sizeof(StructType) % sizeof(ArrayElementType) == 0);
    return reinterpret_cast<const
        ArrayElementType(&)[sizeof(StructType) / sizeof(ArrayElementType)]>(
        data);
}

/**
 * @note    This function is automatically generated by 
 *          `src/logentry/codegen/Codegen.py`.  
 *          Don't edit this file directly, edit the template instead: 
 *          `src/logentry/templates/logger.drone.template.cpp`.
 */
LogEntry getLogData() {
    LogEntry logEntry;
    logEntry.setSize(64);
    logEntry.setMode(int32_t(getFlightMode()));
    logEntry.setFrametime(getMillis());
    logEntry.setFramecounter(getTickCount());
    logEntry.setDroneConfig(configManager.getControllerConfiguration());
    logEntry.setRcTuning(getTuner());
    logEntry.setRcThrottle(getThrottle());
    logEntry.setRcRoll(getRoll());
    logEntry.setRcPitch(getPitch());
    logEntry.setRcYaw(getYaw());
    logEntry.setReferenceOrientation(toCppArray(attitudeController.getReferenceQuat()));
    logEntry.setReferenceOrientationEuler(toCppArray(attitudeController.getReferenceEuler()));
    logEntry.set__pad0(0);
    logEntry.setReferenceHeight(altitudeController.getReferenceHeight());
    logEntry.setReferenceLocation(toCppArray(positionController.getReferencePosition()));
    logEntry.setMeasurementOrientation(toCppArray(getAHRSQuat()));
    logEntry.setMeasurementAngularVelocity(toCppArray(getGyroMeasurement()));
    logEntry.setMeasurementHeight(getCorrectedSonarMeasurement());
    logEntry.setMeasurementLocation(toCppArray(getCorrectedPositionMeasurement()));
    logEntry.setAttitudeObserverState(toCppArray(attitudeController.getStateEstimate()));
    logEntry.setAltitudeObserverState(toCppArray(altitudeController.getStateEstimate()));
    logEntry.setNavigationObserverState(toCppArray(positionController.getStateEstimate()));
    logEntry.setAttitudeYawOffset(getYawJump());
    logEntry.setAttitudeControlSignals(toCppArray(attitudeController.getControlSignal()));
    logEntry.setAltitudeControlSignal(altitudeController.getControlSignal().ut);
    logEntry.setPositionControlSignal(toCppArray(positionController.getControlSignal()));
    logEntry.setMotorControlSignals(toCppArray(getMotorSignals()));
    logEntry.setCommonThrust(getCommonThrust());
    logEntry.setHoverThrust(inputBias.getThrustBias());

    return logEntry;
}